### ISSUE TITLE
GCM Notifications are broken

### ISSUE THREAD

**Issue by ikornaselur** [Ikornaselur/canaritus#46]
Broken after #44 

Log output

```
2015-10-29 00:56:28 - EVENT - Adding event for host <host>: "Health degraded: <host> is down."
/opt/canaritus/src/server/events.js:29
    (0, _notifications.gcmNotification)(config);
                                       ^

TypeError: (0 , _notifications.gcmNotification) is not a function
    at pingClients (/opt/canaritus/src/server/events.js:12:5)
    at Statement.<anonymous> (/opt/canaritus/src/server/events.js:32:7)

```

**Comment by ikornaselur** [comment]
Fixed in #47 (accidentally wrote fixes #44 in commit msg instead of #46 in 4e91ae28cd82cf1adef01860575eb096dd540791)
